language: node_js
env:
  - CXX="g++-4.8"
node_js:
  - "4"
  - "iojs"
  - "iojs-v1"
  - "iojs-v2"
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8
